server:
  port: 8085
spring:
  application:
    name: api-donaciones
  ## MySQL
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/wowfunding
    username: root
    password: topo21
    driver-class-name: com.mysql.cj.jdbc.Driver

#eureka
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceURL:
      defaultZone: http://${IP_EUREKA:localhost}:8761/eureka
#actuator
management:
  #  health:
  #    circuitbreakers:
  #      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
info:
  name: api-donaciones
  description: api-donaciones
  version: 1.0.0
  date: 2023-11-02