server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-donaciones
  datasource:
    username: pi21023c02_GRUPO2
    password: jaiPe0oh
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db.ctd.academy:3306/pi21023c02_GRUPO2
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

info:
  application:
    name: api-donaciones

eureka:
#  instance:
#    hostname: localhost
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

