server:
  port: ${SERVER_PORT:0}

spring:
  application:
    name: api-donaciones
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/wowfunding
    username: root
    password: topo21
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

info:
  application:
    name: api-donaciones

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




