server:
  port: ${SERVER_PORT:0}

spring:
  application:
    name: api-donaciones
  datasource:
    url: jdbc:mysql://db.ctd.academy:3306/${mysql_database}?useSSL=false&serverTimezone=UTC
    username: ${mysql_username}
    password: ${mysql_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

info:
  application:
    name: api-donaciones

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




