server:
  port:  ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users-api
          uri: lb://users-api
          predicates:
            - Path=/users/**

#        - id: msswallet
#          uri: lb://api-wallet
#          predicates:
#            - Path=/wallet/**
#        - id: mssmargins
#          uri: lb://api-margins
#          predicates:
#            - Path=/calculate/**

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

