server:
  port:  ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: api-donaciones
          uri: lb://api-donaciones
          predicates:
            - Path=/api/**
        - id: ms-productos
          uri: lb://ms-productos
          predicates:
            - Path=/api/**
#        - id: mssmargins
#          uri: lb://api-margins
#          predicates:
#            - Path=/calculate/**

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://${IP_EUREKA:localhost}:8761/eureka
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

