server:
  port:  ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: gateway
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:

        - id: users-api
          uri: lb://users-api
          predicates:
            - Path=/users/**
        - id: api-donaciones
          uri: lb://api-donaciones
          predicates:
            - Path=/api-donaciones/**
        - id: mc-productos
          uri: lb://mc-productos
          predicates:
            - Path=/api-productos/**

#cola
queue:
  pi2:
    gp2:
      prductos_donaciones: queue.pi2.gp2.productos_donaciones

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://${IP_EUREKA:localhost}:8761/eureka
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

