server:
  port: ${PORT:8761}

spring:
  application:
    name: ms-discovery

eureka:
  instance:
    hostname: ${IP_EUREKA:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    leaseRenewalIntervalInSeconds: 15
    leaseExpirationDurationInSeconds: 30
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${server.port}/eureka/
