server:
  port: ${PORT:8761}

spring:
  application:
    name: ms-discovery

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    hostname: ${IP_EUREKA:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${server.port}/eureka/
