server:
  port: ${SERVER_PORT:0}

spring:
  application:
    name: users-api
  datasource:
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/users

info:
  application:
    name: users-api

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/