#server:
#  port: ${PORT:8761}

spring:
  application:
    name: ms-discovery
  config:
    import: optional:config-server:${CONFIG_SERVER:http://localhost:8888}


#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance}:${server.port}/eureka/